DROP TABLE Hotel2.Order_Booking_With_Optional 
DROP TABLE Hotel2.Order_Booking 
DROP TABLE Hotel2.Order_Status
DROP TABLE Hotel2.Optional 
DROP TABLE Hotel2.Room 
DROP TABLE Hotel2.Room_Kind 
DROP TABLE Hotel2.Class_Apartment 
DROP TABLE Hotel2.Room_Type 
DROP TABLE Hotel2.User_With_Role
DROP TABLE Hotel2.User 
DROP TABLE Hotel2.User_Status 
DROP TABLE Hotel2.Role
